spring :
    h2 : 
        console : 
            enabled : true
            path : /h2-console
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: 12
        password: 12
    jpa:
        show_sql: true
        hibernate:
            ddl-auto: create

jwt : 
    Header : IamHeader
    secret : thisissecretthisissecretthisissecretthisissecretthisissecretthisissecretthisissecretthisissecretthisissecret
    token-validity-in-seconds : 86400
    access-token-cookie-name : ACCESS_TOKEN
    authorization-header : AUTHORIZATION

server :
    port : 8081