spring :
    h2 : 
        console : 
            enabled : true
            path : /h2-console
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:sookje
        username: 12
        password: 12
    jpa:
        show_sql: true
        hibernate:
            ddl-auto: create